version: '3.9'

services:
  pg_autmel:
    container_name: "pg_autmel"
    hostname: "pg_autmel"
    restart: unless-stopped
    env_file: secret.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ${VOLUMES_PATH}/postgresql/data:/data:/var/postgresql/data
      - ${VOLUMES_PATH}/postgresql/backups/backups
      - ${VOLUMES_PATH}/log/postgresql:/var/log/postgresql
    environment:
      PGDATA: /var/postgresql/data
      POSTGRES_DB: ${PG_DBs}
      POSTGRES_USER: ${PG_USERs}
      POSTGRES_PASSWORD: ${PG_PASSWDs}
      ALLOW_IP_RANGE: ${ALLOW_IP_RANGE}
#      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
      POSTGRES_MULTIPLE_EXTENSIONS: postgis
    networks:
      - autmel-vlan
    healthcheck:
      interval: 60s
      timeout: 30s
      retries: 3
      test: "pg_isready"
  
networks:
  autmel-vlan:
    external: true
